[package]
name = "kobold_hello_world_example"
version = "0.1.0"
edition = "2021"

[dependencies]
kobold = { path = "../../crates/kobold" }
gloo-storage = "0.2.1"
log = "0.4.17"
wasm-bindgen = "0.2.84"
wasm-logger = "0.2.0"
